### ISSUE TITLE
Idea Submission Description Box

### ISSUE THREAD

**Issue by MarkPuchalaII** [coeventer/ccf#134]
The description box is WAY too small to work with when I'm submitting an idea.

I have to scroll all over, and can only view about 8 lines at a time.
Once I'm editing a previously made idea, I can only view 4 lines at a time!

Please make this input box larger?

**Comment by chadfennell** [comment]
Agreed, heh.

**Comment by pete2786** [comment]
Interesting. I hadn't thought about it but good point.

**Comment by pete2786** [comment]
Made it bigger!
