### ISSUE TITLE
User with "deactivated account" can't re-activate their account

### ISSUE THREAD

**Issue by linkalis** [coeventer/ccf#135]
I somehow managed to deactivate my account (can't recall how). Now I can log into the app, see my user icon and profile, but see "Deactivated Account" listed in place of my name. In this state, it won't let the user submit projects, comments, or "like" things.

**Comment by pete2786** [comment]
Short term I cleaned up the data, still need a long term fix with the deactivation disassociation the oauth account. Let me know if you still have issues.

**Comment by linkalis** [comment]
Thanks, Dave! Looks good for my account for now. Will leave this open as a reminder to fix the deactivation issue.

**Comment by pete2786** [comment]
Fixed bug
