### ISSUE TITLE
Anonymization to encourage diversity

### ISSUE THREAD

**Issue by azenk** [coeventer/ccf#137]
We'd like to use co-eventer for an upcoming devops conference.  Specifically we'd like to use it for collecting ideas for open space discussions.  To minimize the impact of implicit biases, and encourage diverse participation, we're trying to anonymize as much of the idea gathering/talk submission process as possible.

Would it be possible to add a toggle for removing names and avatars from proposed projects?  As a second level, it might also be nice to remove the names from likes, volunteers, and maybe even comments.

Ideally we'd still like to be able to use the identity information to figure out how to schedule things so that people can participate in as many things that they're interested in (with or without real names) without conflicts.

**Comment by chadfennell** [comment]
Thanks for submitting this, @azenk ! This seems like a really interesting idea, particularly for submitting new projects - stuff I want to see happen but that I won't necessarily do. 

What would you think about giving users the option to hide their name / submit anonymously? I'm thinking some folks might attribution and others not.

I think I would personally sort of lean towards keeping comments, likes, votes, etc associated with users. I think the quality tends to go up with attribution / accountability. 

The use-case of "somebody should do this project" seems (to me) like it could be fairly useful.

@pete2786 Thoughts?

**Comment by azenk** [comment]
For our case, we were thinking a global event-wide toggle.

**Comment by chadfennell** [comment]
K, good to know. Seems theoretically doable.

**Comment by pete2786** [comment]
@azenk I think anonymizing the ideas/projects would be OK via a per event or per organization setting. 

The downside from my perspective would be a negative impact on a longer term plan (though not much development has happened lately) of ideas bubbling up outside of your organization to a wider community.

**Comment by pete2786** [comment]
I'll look in to this soon, sorry for the delay.

**Comment by pete2786** [comment]
@azenk I have added two settings in the PR listed above: anonymous projects and anonymous social. Former is hiding the owner, latter is hiding the anonymizing like, volunteer and comment. This also included slack integration :-D.

**Comment by azenk** [comment]
Thanks!  I just turned this on for our event.  Exactly what I had in mind.

**Comment by pete2786** [comment]
Cool, could you please take a minute to gather some feedback from others at the event and post some general thoughts here? @azenk

**Comment by azenk** [comment]
We added a question about it to our post event survey.  I'll also solicit some direct feedback.  So far I've only heard positive things.

**Comment by azenk** [comment]
@pete2786 Thanks again for implementing this.  I think it had exactly the effect we were hoping for.  The results from our post event survey question are listed below.  

How useful was the anonymization of the open space submissions (we anonymized
who submitted the open space and who voted for the topic)?

1 Extremely useful 32.61% 15
2 Moderately useful 21.74% 10
3 Slightly useful 13.04% 6
4 Neither useful nor useless 28.26% 13
5 Slightly useless 4.35% 2
6 Moderately useless 0.00% 0
7 Extremely useless 0.00% 0

**Comment by pete2786** [comment]
Thanks for sharing, glad to see it.
