### ISSUE TITLE
"Registration Closed" button should be changed to "Unregister" for existing registered users

### ISSUE THREAD

**Issue by linkalis** [coeventer/ccf#138]
When event is fully registered and no spots are left, the "Register Now" button reads "Registration Closed" for all participants.  This, unfortunately, locks existing registered users out of unregistering themselves from the event if the event is full.  Desired behavior:

- If an event is full, but a participant is already registered, the button should read "Unregister".

- If an event is full, and a participant views the page who is not yet registered, the button should read "Registration Closed".

**Comment by pete2786** [comment]
Thanks, will fix soon.

**Comment by pete2786** [comment]
@linkalis it's done, sorry for the slow turnaround!
