### ISSUE TITLE
Allow admins to make some minor UI changes to better fit their events

### ISSUE THREAD

**Issue by wbushey** [coeventer/ccf#139]
Hi again. The next Geo:Code is coming up in early March, and we are again going to use CoEventer for registration and idea submission. One major difference about this year's Geo:Code is that it will be an unconference plus a hack space. Since both events are ultimately based on participants suggesting ideas and working on/discussing those same ideas, the primary features of CoEventer translate very well to an unconference.

The only changes I've heard suggested or have considered myself are some minor changes to the UI around ideas/projects. E.g. changing 'Proposed Project Ideas' to 'Prosed Sessions', or changing the 'Repository' link field on the idea submission form to a general 'Link' field.

Realizing that changes for one particular event probably won't make sense for other events, I was thinking, let's make these attributes on the event, with the default values being what they currently are. This way, admins could customize certain prompts and UI elements to fit the theme or feel of their event.

A list of items I'm thinking could have customizable text include:
 - 'Submit An Idea'
 - 'Proposed Project Ideas'
 - 'Repository'

**Comment by pete2786** [comment]
I think it makes sense. The app has badly needed an "Organization settings" model or a settings model which lives outside of the organization/event models. These could live there with sensible defaults.

**Comment by dazzaji** [comment]
+1  I'm also looking at CoEventer for a blended hackathon/unconference that I'm helping to organize (here: http://www.mclegalhackathon.org/#unconference).  Please make some noise if you start hacking an event setting and I'll help if I'm technically able or we could probably gather some people at the next hack night to give a hand (here: https://www.meetup.com/Massachusetts-Legal-Hackers/events/237695426)

**Comment by pete2786** [comment]
Good to know. I'll see if we can make this happen soon.

**Comment by dazzaji** [comment]
@pete2786 thanks - I look forward to trying it out.

**Comment by pete2786** [comment]
This is done, so far I only added the things mentioned specifically by you @wbushey

**Comment by wbushey** [comment]
Thanks @pete2786. I just tried it on out on http://opentwincities.coeventer.com/events/32-geo-code-2017, and it works great.

**Comment by pete2786** [comment]
np, thanks for the idea!
