### ISSUE TITLE
Emails not sending?

### ISSUE THREAD

**Issue by ballPointPenguin** [coeventer/ccf#151]
I'm not sure if this is the right place for this ticket, but when signing up for http://www.hennepin.us/geocode I am not receiving an email verification. Interacting with http://coeventer.com/users/set_email seems to have no effect. Emails are not appearing in my inbox, spam folder, or any other folder. Thus I am unable to sign in.

**Comment by ballPointPenguin** [comment]
ok I tried a different email address and it worked. hmmm

**Comment by pete2786** [comment]
I looked in the logs, could have been an issue with the email provider we use.
