### ISSUE TITLE
Suggest similar projects when user is Submitting an Idea

### ISSUE THREAD

**Issue by wbushey** [coeventer/ccf#73]
Like #72, I don't know if this is something Campus Codefest has experienced, but we've definitely seen event participants suggest project ideas that are very similar to previously suggested or worked on ideas. It seems to me there is an opportunity here to help participants find others who are interested in similar ideas, to learn from what others have done, or to join projects that are already underway. One way to do this could be to have CCF search existing projects while the user is entering an idea title, then display any found projects to the user, suggesting they take a look at those projects before submitting a new idea.

**Comment by pete2786** [comment]
@chadfennell Thoughts on how we could approach this problem?

**Comment by chadfennell** [comment]
@pete2786 Yeah, I am thinking I can achieve a pretty decent similar project recommender service via Solr. I have been hoping to implement event, organization, and cross-organization project search at some point. This feature could be part of that effort. I don't think this feature would be too hard and would be really cool.

**Comment by pete2786** [comment]
Closing for now, please re-open if/when we can consider recommender service.
