### ISSUE TITLE
User would like to register in CoEventer

### ISSUE THREAD

**Issue by cre8ivecubed** [coeventer/ccf#96]
User requested means to register within CoEventer as they are without FB, Google or MU account. Yes, understanding that this seems impossible that one has managed to go without FB, Google or Meetup until now -- we are working with community and community members have different levels of trust/comprehension of the digital realm. We wish at all times to be inclusive so this might be an enhancement idea. Thanks for considering!

"A user has contacted you via the contact form: Name: M. McGilp Email: mmcgilp@hclib.org Hello, I would like to register for Geo:Code 2.0 but do not have an account with Facebook, Google or MeetUp. Is there something I'm missing? Is there another way to register? Thank-you, Molly"

**Comment by pete2786** [comment]
I would prefer to keep the complexity of user identity management external to the application. Easiest solution, I would suggest the user create a meet up account, as this was implemented specifically for OpenTC/this event.

I would also be open to adding Open Id (http://openid.net/) as an auth provider, or something else which is popular enough to have many users, if the user has any suggestions.

**Comment by wbushey** [comment]
I like the idea of OpenID, but it has [a user experience](http://openid.net/get-an-openid/start-using-your-openid/) that is unfamiliar to most people (provide an identity URL - something that most people are not familiar with - *then* a username and password). It's times like this that make sad to know that [Mozilla Personas](https://developer.mozilla.org/en-US/Persona) is shutting down.

I think there are a couple of issues underlying this discussion:
 - Trust/reputation of our authentication providers. Some users will have legitimate reasons for not having/wanting an account with Facebook or Google, and that is something we should respect.
 - Choice and [Overchoice](https://en.wikipedia.org/wiki/Overchoice). Providing multiple login options is one way to address the above reputation problem. It's also a way to provide a quick path to logging in for people who have one of our supported accounts. But we can't go too far with this - adding more and more options - or the login screen will become a confusing mess. 

  This choice also makes the scenario we're talking about - a user needs to create an identity - more complicated. Now the user needs to make a decision that they would not need to make if there were only one login option (regardless of it being login via CoEventer or a single third party).

A related issue might be that it is not clear to users that they can signup for the services we are using for login.

More and more I'm thinking, we should simply add a sentence at the bottom of the login modal like: "Don't have an account with one of the above? <button>Click here</button> to sign up with <default login of org>".

**Comment by pete2786** [comment]
Thanks, that is some great input @wbushey. I was not terrible familiar with Open Id and did not realize it was such a pain.

I like the simple solution. It also points to the need for a better Organization settings model. Something like a JSON object which can be more flexible than adding a column to a table every time. Might not be something we get in for this issue but it needs to happen either way.

**Comment by mjhoy** [comment]
speaking as a user, i find linking accounts frustrating and usually it drives me away from registering, unless it's something that very obviously needs to be linked (e.g. travis-ci and github).

**Comment by pete2786** [comment]
@mjhoy I'm not sure what you mean by a linked account. Do you mean using creating a local, app specific identity versus a third party (Google, etc) to authenticate?

**Comment by mjhoy** [comment]
sorry, i meant authenticating via google/fb/etc.

1. i don't like giving a new service any more information than i need to
2. i can never remember which identity i used
3. as @wbushey points out there is no one choice highlighted and it's not clear what i should choose (will I have to log in to google if i click google? or facebook? maybe i don't want my FB identity revealed? ..etc). in the case of registration plus authentication through other services, usually registration is highlighted and i don't need to think about it.

i may not be a typical user because i have a password manager that makes registering for new services very easy.

**Comment by pete2786** [comment]
Got it, thanks for clarifying. I also use a password manager but find myself doing a bit of local identity versus third party. Points 2/3 are definitely well taken. As I mentioned, at this time I don't anticipate undertaking an effort to add local account creation, but I'd imagine demand will only grow as the audience increases.

**Comment by mjhoy** [comment]
@pete2786 also, as a related but somewhat orthogonal issue, it makes local development annoying if you don't have an internet connection. (perhaps just me, but often i'm hacking at a wifi-less coffee shop or library.) what do you think about adding the `developer` provider in the case of `Rails.env.development?` -- see here http://www.rubydoc.info/github/intridea/omniauth/OmniAuth/Strategies/Developer

**Comment by pete2786** [comment]
Good idea, I like that. I have run in to the same issue when trying to develop while on a long flight.
